### ISSUE TITLE
Ca

### ISSUE THREAD

**Issue by Mmehdi06** [raycast/extensions-swift-tools#2]
Swift Code:

```swift
import AppKit
import RaycastExtensionMacro


#exportFunction(close)
func close() {
    guard let frontmostApplication = NSWorkspace.shared.frontmostApplication else {
        return
    }
    
    var excludedBundleIdentifiers = ["com.apple.finder", "com.apple.dt.Xcode"]
    if let frontmostAppBundleIdentifier = frontmostApplication.bundleIdentifier {
        excludedBundleIdentifiers.append(frontmostAppBundleIdentifier)
    }

    NSWorkspace.shared.runningApplications
        .filter {
            $0 != NSRunningApplication.current
                && $0.activationPolicy == .regular
                && !excludedBundleIdentifiers.contains($0.bundleIdentifier ?? "")
        }
        .forEach { $0.terminate() }

    print("Quit all applications except Xcode and \(String(describing: frontmostApplication.localizedName))")
}


#handleFunctionCall()
```

---------------------------------------------------------------------------------------------------------------------------

Extension Code:
```js
import { showHUD, getFrontmostApplication } from "@raycast/api";
import {close} from "../swift/MyExecutable/Sources/main.swift"

export default async function main() {
  const frontMostApp = await getFrontmostApplication();

  close();

 
  await showHUD("Frontmost App: " + frontMostApp.name);
}
```

---------------------------------------------------------------------------------------------------------------------------

Error:
	"message": "Cannot find module '../swift/MyExecutable/Sources/main.swift' or its corresponding type declarations.",

![CleanShot 2023-11-27 at 22 19 25@2x](https://github.com/raycast/raycast-extension-macro/assets/115171530/3260a50f-0cb9-47b6-bfe9-f95861c01b0c)

**Comment by mathieudutour** [comment]
Try just `import {close} from "../swift/MyExecutable"`

**Comment by unnamedd** [comment]
@Mmehdi06 what you are going to use is the executable you already created, in this case, it's name is going to be `MyExecutable` that's why @mathieudutour in the reply above suggested you that. Your `main.swift` won't  be accessed because the extension is not trying to consume a Swift file code, but an interface generated by your executable. 😉

**Comment by Mmehdi06** [comment]
![CleanShot 2023-11-29 at 18 56 30](https://github.com/raycast/raycast-extension-macro/assets/115171530/3be9e1cc-c81c-433c-bc9f-d9997b54ac95)


I thank you two for your help but can't figure it out still, i am new to programming so might be doing something basic wrong.
I still get the same error

**Comment by mathieudutour** [comment]
Ah sorry it's `import {close} from "swift:../swift/MyExecutable"`

**Comment by Mmehdi06** [comment]
![CleanShot 2023-11-30 at 09 55 29@2x](https://github.com/raycast/raycast-extension-macro/assets/115171530/1bc578c0-8d79-4652-84e2-9c356e675ccb)

I am sorry to disturb you longer than needed, but it still does not work, same error: Cannot find module 'swift:../swift/MyExecutable' or its corresponding type declarations.ts(2307)

**Comment by mathieudutour** [comment]
What version of `@raycast/api` are you using (in package.json)? Can you update to the latest one?

**Comment by Mmehdi06** [comment]
I was using: "@raycast/api": "^1.62.2",
Just updated to : "@raycast/api": "^1.63.0",

But same error still occurs

**Comment by mathieudutour** [comment]
Can you try building the extension (`npm run dev`) and see if it fixes it?

**Comment by Mmehdi06** [comment]
![CleanShot 2023-11-30 at 11 06 17@2x](https://github.com/raycast/raycast-extension-macro/assets/115171530/941ee85b-e1ff-45f3-82a9-fecc2a0bc3a3)

Thank you a lot. It now works, it compiled the swift package than the error code disappeared
