### ISSUE TITLE
Failed creating file (open /IDEWorkspaceChecks.plist: permission denied)

### ISSUE THREAD

**Issue by Mmehdi06** [raycast/extensions-swift-tools#5]
I am trying to update my extension but when running npm run publish, get the following error at the stage of "checking for new contributions":

```shell
npm run publish
> publish
> npx @raycast/api@latest publish

ready -  validate git repository
ready -  getting fork
ready -  preparing clone
wait  -  checking for new contributions.failed creating file (open /Users/mehdimerkachi/Developer/Raycast-Extensions/keep-frontmost/QuitAllButFocused/.raycast-swift-build/SourcePackages/checkouts/raycast-extension-macro/.swiftpm/xcode/package.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist: permission denied)
```

I updated npm and the raycast API. I have build the extension and the extension works. Now I would like to publish it.

**Comment by grzegorzkrukowski** [comment]
Hey @Mmehdi06 

Can you check if you have proper write permissions to `.raycast-swift-build` folder in your extension directory.

Also you can try deleting it first, then try running the `publish` again so it will be recreated on the user permissions that is running the command.

**Comment by Mmehdi06** [comment]
> Hey @Mmehdi06 
> 
> 
> 
> Can you check if you have proper write permissions to `.raycast-swift-build` folder in your extension directory.
> 
> 
> 
> Also you can try deleting it first, then try running the `publish` again so it will be recreated on the user permissions that is running the command.

Thank you, it now works !
